name: Deploy to Vercel

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check for Lock File
        run: |
          if [ ! -f package-lock.json ] && [ ! -f npm-shrinkwrap.json ] && [ ! -f yarn.lock ];
            then echo "Error: No lock file found! Ensure you have committed a lock file."
          exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # LTS version of Node
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run check

      - name: Lint & Format Check
        run: npm run lint

      - name: Build
        run: npm run build
